
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - newgroup.adva.domain
  resources:
  - simpleingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - newgroup.adva.domain
  resources:
  - simpleingresses/status
  verbs:
  - get
  - patch
  - update
